default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: fullylife_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: fullylife_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: fullylife_production
    username: postgres
    password: postgres
  cache:
    <<: *primary_production
    database: fullylife_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: fullylife_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: babel_goods_production_cable
    migrations_paths: db/cable_migrate
